/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_hotel_12407;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ryuu
 */
public class Menu_Utama extends javax.swing.JFrame {
    Connection conn;
    Statement stm;
            String url = "jdbc:mysql://localhost/pbo_hotel_12407";
            String user = "root";
            String pass = "";

    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelDataTamu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Navbar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        btnTamu = new javax.swing.JMenuItem();
        btnKamar = new javax.swing.JMenuItem();
        btnCheckin = new javax.swing.JMenuItem();
        btnCheckout = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        lapKamarTersedia = new javax.swing.JMenuItem();
        lapKamarKosong = new javax.swing.JMenuItem();
        lapTamu = new javax.swing.JMenuItem();
        lapCheckin = new javax.swing.JMenuItem();
        lapCheckout = new javax.swing.JMenuItem();
        lapLaporanHotel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContent.setBackground(new java.awt.Color(0, 0, 0));
        panelContent.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryuu\\Downloads\\HotelReyhan_Logo-circle-resize.png")); // NOI18N
        panelHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryuu\\Downloads\\Why_Hotel_Reyhan-resize.png")); // NOI18N
        panelHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        jLabel3.setText("Welcome to Hotel Reyhan");
        panelHome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        panelContent.add(panelHome, "card2");

        panelDataTamu.setBackground(new java.awt.Color(0, 0, 0));
        panelDataTamu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryuu\\Downloads\\HotelReyhan_Logo-circle-resize.png")); // NOI18N
        panelDataTamu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Check-in Hotel Reyhan");
        panelDataTamu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        panelContent.add(panelDataTamu, "card3");

        jMenu1.setText("Home");
        Navbar.add(jMenu1);

        jMenu2.setText("Data & Transaksi");

        btnTamu.setText("Data Tamu");
        btnTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamuActionPerformed(evt);
            }
        });
        jMenu2.add(btnTamu);

        btnKamar.setText("Data Kamar");
        btnKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKamarActionPerformed(evt);
            }
        });
        jMenu2.add(btnKamar);

        btnCheckin.setText("Check-in");
        btnCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckinActionPerformed(evt);
            }
        });
        jMenu2.add(btnCheckin);

        btnCheckout.setText("Check-out");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        jMenu2.add(btnCheckout);

        Navbar.add(jMenu2);

        jMenu3.setText("Laporan");

        lapKamarTersedia.setText("Kamar Tersedia");
        lapKamarTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapKamarTersediaActionPerformed(evt);
            }
        });
        jMenu3.add(lapKamarTersedia);

        lapKamarKosong.setText("Kamar Terisi");
        lapKamarKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapKamarKosongActionPerformed(evt);
            }
        });
        jMenu3.add(lapKamarKosong);

        lapTamu.setText("Tamu");
        lapTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapTamuActionPerformed(evt);
            }
        });
        jMenu3.add(lapTamu);

        lapCheckin.setText("Tamu Check-in");
        lapCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapCheckinActionPerformed(evt);
            }
        });
        jMenu3.add(lapCheckin);

        lapCheckout.setText("Tamu Check-out");
        lapCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapCheckoutActionPerformed(evt);
            }
        });
        jMenu3.add(lapCheckout);

        lapLaporanHotel.setText("Laporan Hotel");
        lapLaporanHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapLaporanHotelActionPerformed(evt);
            }
        });
        jMenu3.add(lapLaporanHotel);

        Navbar.add(jMenu3);

        setJMenuBar(Navbar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckinActionPerformed
        try {
            // TODO add your handling code here:
            new Check_in().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCheckinActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        try {
            // TODO add your handling code here:
            new Check_out().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void lapLaporanHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapLaporanHotelActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\UAS_Hotel_12407\\src\\uas_hotel_12407\\laporan.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapLaporanHotelActionPerformed

    private void lapKamarTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapKamarTersediaActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\UAS_Hotel_12407\\src\\uas_hotel_12407\\dataKamar.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapKamarTersediaActionPerformed

    private void lapTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapTamuActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\UAS_Hotel_12407\\src\\uas_hotel_12407\\dataTamu.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapTamuActionPerformed

    private void lapCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapCheckinActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\UAS_Hotel_12407\\src\\uas_hotel_12407\\dataCheckin.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapCheckinActionPerformed

    private void lapCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapCheckoutActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\UAS_Hotel_12407\\src\\uas_hotel_12407\\dataCheckout.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapCheckoutActionPerformed

    private void btnTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamuActionPerformed
        try {
            // TODO add your handling code here:
            new Tamu().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTamuActionPerformed

    private void lapKamarKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapKamarKosongActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\UAS_Hotel_12407\\src\\uas_hotel_12407\\dataKamarTerisi.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapKamarKosongActionPerformed

    private void btnKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKamarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new Kamar().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Navbar;
    private javax.swing.JMenuItem btnCheckin;
    private javax.swing.JMenuItem btnCheckout;
    private javax.swing.JMenuItem btnKamar;
    private javax.swing.JMenuItem btnTamu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem lapCheckin;
    private javax.swing.JMenuItem lapCheckout;
    private javax.swing.JMenuItem lapKamarKosong;
    private javax.swing.JMenuItem lapKamarTersedia;
    private javax.swing.JMenuItem lapLaporanHotel;
    private javax.swing.JMenuItem lapTamu;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelDataTamu;
    private javax.swing.JPanel panelHome;
    // End of variables declaration//GEN-END:variables
}
